#Protection Stones Configuration Page

#Specify the block you want to use to protect regions. Use names from https://goo.gl/EBM8w5
Block: BEDROCK

#Specify the default flags to be set when a new protected region is created..
Flags:
  - use deny
  - pvp deny
  - greeting &aGebiet von %player%
  - farewell &aBis bald

#List all the flags that can be set by region owners. Separate them with a comma, no space.
Allowed Flags: use,pvp,greeting,farewell,mob-spawning

#Toggle UUID support for protected regions.
#Has no real effect. If set to false your computer may explode.
UUID: true

#Protected Region Configuration
Region:
  X Radius: 20
  #Set Y to -1 if you want it to protect from sky to bedrock.
  Y Radius: -1
  Z Radius: 20
#Auto Hide also has no real effect. Stone will be hidden anyways.
  Auto Hide: true
  No Drop: true
  Block Piston: true

#Set priority of all protected regions.
Priority: 0
